<?php
/** INSERTAR LA INFORMACION EN LA TABLA FAC DETALLE FACTURA */
/* VAMOS A INCLUIR LA CLASE CONEXION */

require( '../../../nuevo_sia_v2/conection/conexion_ibs.php' );
require( '../../../nuevo_sia_v2/conection/conexion_sql.php' );
require( '../../../general_funciones.php' );

$time_pre = microtime( true );

$db2conp = new con_ibs( '',odbc, odbc );
echo ( !$db2conp )?'<br> ERROR CONEXION A IBS<br>' :'';

$sqlcon = new con_sql( 'SQLFACTURAS' );
echo ( !$sqlcon )?'<br> ERROR CONEXION A SQLSERVER<br>' :'';
mssql_select_db( 'SQLFACTURAS' );

$fecha_de_hoy = date( 'Ymd' );
$fecha_de_hoy_menos_1_meses = date( 'Ymd', strtotime( $fecha_de_hoy.'- 1 month' ) );

$arreglo_insert_table = '';
/* fechas formato aaammdd */
$fechaActual = date( 'Ymd' );
$ini_corte   =  date( 'Ym', strtotime( $fechaActual.'- 2 month' ) ).'16';
$fin_corte   =  date( 'Ym', strtotime( $fechaActual ) ).'15';


// $ini_corte   =  '20221015';




/** ELIMIAR REGISTRO DE 2 DIAS HACIA ATRAS !POR FAVOR NO DESOCUPAR LA TABLA¡ */
// AND LINEA_ORDEN IN ( 10, 20, 30 )

mssql_query( "delete from dbo.FACDETALLEFACTURANEW_EVENTO where FECHAORDEN >= '$fechaActual'" );
$ejecutar_consulta = 2;
$insert_detalle_fac = (
    "INSERT INTO [dbo].[FACDETALLEFACTURANEW_EVENTO](
		[Tipo]
		,[Factura]
		,[Fecha]
		,[FechaOrden]
		,[Cedula]
		,[NombreCliente]
		,[Bodega]
		,[Vendedor]
		,[DesVendedor]
		,[Call]
		,[Manejador]
		,[Linea]
		,[Item]
		,[Descripcion]
		,[FOC]
		,[Grupo]
		,[Segmento]
		,[Familia]
		,[Cantidad]
		,[ValorSinIVA]
		,[ValorIVA]
		,[Valor]
		,[Planeador]
		,[Sector])
	VALUES " );

    /** RECORREMOS PRIMERO LAS  FECHAS PARA LIMITAR LA CONSULTA */
    $sql_rondas = ( "SELECT distinct(FECHA_ORDEN) FECHA_ORDEN FROM AGR620CFAG.VISVENTASORDEN1 WHERE FECHA_ORDEN >='$fechaActual' order by fecha_orden" );
    $rta_sql_ibs_f = $db2conp->conectar( $sql_rondas );



    while( $fechas = odbc_fetch_array( $rta_sql_ibs_f ) ) {
        $arreglo_insert_table = '';

        if ( $ejecutar_consulta == 1 ) {

            $sql_ibs_1_meses = ( "
	SELECT
	TIPO,
	FACTURA,
	FECHA_FACTURA,
	FECHA_ORDEN,
	LTRIM(RTRIM(CLIENTE)) AS CEDULA,
	LTRIM(RTRIM(NOMBRE_CLIENTE)) AS NOMBRE_CLIENTE,
	BODEGA,
	LTRIM(RTRIM(VENDEDOR)) AS  VENDEDOR,
	LTRIM(RTRIM(DES_VENDE)) AS DES_VENDE,
	LTRIM(RTRIM(CALL)) AS CALL,
	MANEJADOR,
	LINEA_ORDEN AS LINEA,
	LTRIM(RTRIM(CODIGO)) AS ITEM,
	LTRIM(RTRIM(DESCRIPCION)) AS DESCRIPCION,
	(CASE WHEN FOC='N'THEN 0 ELSE 1 END )FOC,
	LTRIM(RTRIM(GRUPO)) AS GRUPO,
	SEGMENTA AS SEGMENTO,
	LTRIM(RTRIM(FAMILIA)) AS FAMILIA,
	CANTIDAD,
	VLR_EXC_IVA AS VALORSINIVA,
	VLR_IVA AS IVA,
	VLR_INC_IVA VALOR
	FROM
	AGR620CFAG.VISVENDT
	WHERE FECHA_ORDEN = '$fechas[FECHA_ORDEN]'
	" );
        } else {

            $sql_ibs_1_meses = ( "
	SELECT DISTINCT 	 
			SRBSOH.OHORDT AS TIPO, 
			SRBISH.IHINVN AS FACTURA, 
			SRBISH.IHIDAT AS FECHA_FACTURA, 
			SRBISH.IHODAT AS FECHA_ORDEN, 
			SRBISD.IDCUNO AS CEDULA, 
			SRBNAM.NANAME AS NOMBRE_CLIENTE, 
			SRBISD.IDSROM AS BODEGA, 
		(CASE SRBISD.IDINUM WHEN 0 THEN SRBISH.IHSALE ELSE SRBISH_1.IHSALE END     )AS VENDEDOR, 
		(CASE SRBISD.IDINUM WHEN 0 THEN SRBCTLSD.CTNAME ELSE SRBCTLSD_1.CTNAME END )AS DES_VENDE, 
		(CASE SRBISD.IDINUM WHEN 0 THEN SRBSOH.OHHAND ELSE SRBSOH_1.OHHAND END 	   )AS CALL, 
		(CASE SRBISD.IDINUM WHEN 0 THEN SRBCTLSD.CTSMAN ELSE SRBCTLSD_1.CTSMAN END )AS MANEJADOR, 
		SRBISD.IDOLIN AS LINEA, 
		SRBPRG.PGPRDC AS ITEM,
		SRBPRG.PGDESC AS Descripcion, 
		CASE WHEN SRBISD.IDFOCC='N' THEN 0 ELSE 1 END AS FOC, 
		CASE WHEN (SRBPRG.PGPDGR='G03' AND (SRBCTLSD.CTSMAN='ADMINISTRA' OR SRBCTLSD_1.CTSMAN='ADMINISTRA') AND (SRBSOH.OHHAND='VEND999' OR SRBSOH_1.OHHAND='VEND999')) THEN 'AGI' 
		WHEN (SRBPRG.PGPDGR='G04' AND (SRBCTLSD.CTSMAN='ADMINISTRA' OR SRBCTLSD_1.CTSMAN='ADMINISTRA') AND (SRBSOH.OHHAND='VEND999' OR SRBSOH_1.OHHAND='VEND999')) THEN 'AMI' 
		ELSE SRBPRG.PGPGRP END GRUPO, 
		SRBPRG.PGISET AS SEGMENTO,
		CASE WHEN (SRBCTLPB.PBDESC='IMPORTADOS' AND SRBPRG.PGPDGR='G03' AND (SRBCTLSD.CTSMAN='ADMINISTRA' OR SRBCTLSD_1.CTSMAN='ADMINISTRA') AND (SRBSOH.OHHAND='VEND999' OR SRBSOH_1.OHHAND='VEND999')) THEN 'AGI' 
		WHEN (SRBCTLPB.PBDESC='IMPORTADOS' AND SRBPRG.PGPDGR='G04' AND (SRBCTLSD.CTSMAN='ADMINISTRA' OR SRBCTLSD_1.CTSMAN='ADMINISTRA') AND (SRBSOH.OHHAND='VEND999' OR SRBSOH_1.OHHAND='VEND999')) THEN 'AMI' 
		ELSE SRBCTLPB.PBDESC END FAMILIA,
		(CASE SRBISH.IHTYPP WHEN 1 THEN SRBISD.IDQTY ELSE SRBISD.IDQTY * -1 END) AS CANTIDAD, 
		(CASE WHEN SRBSOL.OLFOCC='Y' THEN 0 ELSE SRBSOL.OLITET END) AS VALORSINIVA,
		CASE SRBISD.IDTYPP WHEN 1 THEN SRBISD.IDITT ELSE SRBISD.IDITT*-1 END AS IVA,  
		(CASE WHEN SRBSOL.OLFOCC='Y' THEN 0 ELSE SRBSOL.OLITIT END) AS VALOR,
		(CASE 
		WHEN (CASE SRBISD.IDINUM WHEN 0 THEN SRBSOH.OHHAND ELSE SRBSOH_1.OHHAND END)<>SRBCTLSD.CTSIGN OR  (CASE SRBISD.IDINUM WHEN 0 THEN SRBCTLSD.CTSMAN ELSE SRBCTLSD_1.CTSMAN END )='MERCADEO' THEN 'MERCADEO'
		WHEN (CASE SRBISD.IDINUM WHEN 0 THEN SRBSOH.OHHAND ELSE SRBSOH_1.OHHAND END)<>SRBCTLSD.CTSIGN OR  SRBISD.IDCUNO  IN ('900423563') THEN 'PESTAR'
		WHEN (CASE SRBISD.IDINUM WHEN 0 THEN SRBSOH.OHHAND ELSE SRBSOH_1.OHHAND END)<>SRBCTLSD.CTSIGN OR  (CASE SRBISD.IDINUM WHEN 0 THEN SRBISH.IHSALE ELSE SRBISH_1.IHSALE END)      ='VEND157'    OR   (CASE SRBISD.IDINUM WHEN 0 THEN SRBISH.IHSALE ELSE SRBISH_1.IHSALE END) ='SUAREZM' 		OR   (CASE SRBISD.IDINUM WHEN 0 THEN SRBISH.IHSALE ELSE SRBISH_1.IHSALE END) ='SUAREZC'    OR (CASE SRBISD.IDINUM WHEN 0 THEN SRBISH.IHSALE ELSE SRBISH_1.IHSALE END) = 'VEND217' OR SRBISD.IDCUNO  IN ('800159998') THEN 'INSTITUCIONAL' 
		WHEN (CASE SRBISD.IDINUM WHEN 0 THEN SRBSOH.OHHAND ELSE SRBSOH_1.OHHAND END)<>SRBCTLSD.CTSIGN OR  (CASE SRBISD.IDINUM WHEN 0 THEN SRBSOH.OHHAND ELSE SRBSOH_1.OHHAND END)      ='MARTINEZF'  OR   (CASE SRBISD.IDINUM WHEN 0 THEN SRBSOH.OHHAND ELSE SRBSOH_1.OHHAND END) ='RODRIGUEZJ' 	THEN 'TRASLADOS'
		WHEN (CASE SRBISD.IDINUM WHEN 0 THEN SRBSOH.OHHAND ELSE SRBSOH_1.OHHAND END)<>SRBCTLSD.CTSIGN OR  (CASE SRBISD.IDINUM WHEN 0 THEN SRBSOH.OHHAND ELSE SRBSOH_1.OHHAND END)      ='ALIANZAS'   OR   (CASE SRBISD.IDINUM WHEN 0 THEN SRBSOH.OHHAND ELSE SRBSOH_1.OHHAND END) ='NETSTORE' 		OR   (CASE SRBISD.IDINUM WHEN 0 THEN SRBSOH.OHHAND ELSE SRBSOH_1.OHHAND END) ='VEND528'    OR (CASE SRBISD.IDINUM WHEN 0 THEN SRBSOH.OHHAND ELSE SRBSOH_1.OHHAND END) ='VEND561' OR (CASE SRBISD.IDINUM WHEN 0 THEN SRBISH.IHSALE ELSE SRBISH_1.IHSALE END) ='VEND417' OR SRBISD.IDCUNO  IN ('1056028493',          '9007487391', '900844137',   '901295969',             '1020775290', '10207752909',           '901128047',    '9011280475', '900041991',   '9006676820',             '79592537',      '901325040',   '1098716630', '901425454',    '901333960',   '52970714',      '900525765',             '9008438989', '9008438984', '9008438981', '9008438982', '901110407',   '9011104074', '1056028493',             '9007487391', '900844137',   '901295969',   '901128047',    '1020775290', '10207752909',             '9011280475', '900770206',   '9007702068', '52430443',      '9006676820', '79592537',      '901325040',             '1098716630', '901425454',   '901333960', '900839095', '9008390956') THEN 'CANALES DIGITALES'
		WHEN (CASE SRBISD.IDINUM WHEN 0 THEN SRBSOH.OHHAND ELSE SRBSOH_1.OHHAND END)<>SRBCTLSD.CTSIGN OR  (CASE SRBISD.IDINUM WHEN 0 THEN SRBSOH.OHHAND ELSE SRBSOH_1.OHHAND END) LIKE 'VENDWEB%'    OR   (CASE SRBISD.IDINUM WHEN 0 THEN SRBSOH.OHHAND ELSE SRBSOH_1.OHHAND END) LIKE 'DIGITAL%' 	OR   (CASE SRBISD.IDINUM WHEN 0 THEN SRBSOH.OHHAND ELSE SRBSOH_1.OHHAND END) ='INTEGRATOR' OR (CASE SRBISD.IDINUM WHEN 0 THEN SRBSOH.OHHAND ELSE SRBSOH_1.OHHAND END) = 'ESTADISTIC' THEN 'PAGINA WEB'
		WHEN (CASE SRBISD.IDINUM WHEN 0 THEN SRBSOH.OHHAND ELSE SRBSOH_1.OHHAND END)= SRBCTLSD.CTSIGN AND (CASE SRBISD.IDINUM WHEN 0 THEN SRBCTLSD.CTSMAN ELSE SRBCTLSD_1.CTSMAN END)  ='VANANDELL'  AND  (CASE SRBISD.IDINUM WHEN 0 THEN SRBSOH.OHHAND ELSE SRBSOH_1.OHHAND END) <> 'VANANDELL' 	AND  (CASE SRBISD.IDINUM WHEN 0 THEN SRBISH.IHSALE ELSE SRBISH_1.IHSALE END) IN ('VEND114', 'VEND214') THEN 'TELEOPERADOR CONSULTORIO'
		WHEN (CASE SRBISD.IDINUM WHEN 0 THEN SRBSOH.OHHAND ELSE SRBSOH_1.OHHAND END)= SRBCTLSD.CTSIGN AND (CASE SRBISD.IDINUM WHEN 0 THEN SRBCTLSD.CTSMAN ELSE SRBCTLSD_1.CTSMAN END)  ='VANANDELL'  AND  (CASE SRBISD.IDINUM WHEN 0 THEN SRBSOH.OHHAND ELSE SRBSOH_1.OHHAND END) <> 'VANANDELL' 	THEN 'TELEOPERADOR EXTERNA'
		WHEN (CASE SRBISD.IDINUM WHEN 0 THEN SRBSOH.OHHAND ELSE SRBSOH_1.OHHAND END)= SRBCTLSD.CTSIGN OR  (CASE SRBISD.IDINUM WHEN 0 THEN SRBISH.IHSALE ELSE SRBISH_1.IHSALE END) 	   ='VENDECOM'   THEN 'CALLCENTER'
		WHEN (CASE SRBISD.IDINUM WHEN 0 THEN SRBSOH.OHHAND ELSE SRBSOH_1.OHHAND END)<>SRBCTLSD.CTSIGN OR  (CASE SRBISD.IDINUM WHEN 0 THEN SRBCTLSD.CTSMAN ELSE SRBCTLSD_1.CTSMAN END ) ='VANANDELL'  AND  (CASE SRBISD.IDINUM WHEN 0 THEN SRBISH.IHSALE ELSE SRBISH_1.IHSALE END) = 'VENDOTC' 		THEN 'VENTA EXTERNA LICITACIONES'
		WHEN (CASE SRBISD.IDINUM WHEN 0 THEN SRBSOH.OHHAND ELSE SRBSOH_1.OHHAND END)<>SRBCTLSD.CTSIGN OR  (CASE SRBISD.IDINUM WHEN 0 THEN SRBCTLSD.CTSMAN ELSE SRBCTLSD_1.CTSMAN END ) ='ADMINISTRA' OR   (CASE SRBISD.IDINUM WHEN 0 THEN SRBSOH.OHHAND ELSE SRBSOH_1.OHHAND END) LIKE 'CAJA%' 		OR   (CASE SRBISD.IDINUM WHEN 0 THEN SRBSOH.OHHAND ELSE SRBSOH_1.OHHAND END) ='VEND999' THEN 'ALMACEN'
		WHEN (CASE SRBISD.IDINUM WHEN 0 THEN SRBSOH.OHHAND ELSE SRBSOH_1.OHHAND END)<>SRBCTLSD.CTSIGN OR  (CASE SRBISD.IDINUM WHEN 0 THEN SRBCTLSD.CTSMAN ELSE SRBCTLSD_1.CTSMAN END ) ='VANANDELL'  THEN 'VENTA EXTERNA'
		END) AS SECTOR
FROM 
		AGR620CFAG.SROISH SRBISH 
		LEFT JOIN AGR620CFAG.SROISDPL SRBISD ON SRBISH.IHINVN = SRBISD.IDINVN AND SRBISH.IHORNO = SRBISD.IDORNO 
		LEFT JOIN AGR620CFAG.SRONAM SRBNAM ON SRBNAM.NANUM=SRBISD.IDCUNO 
		LEFT JOIN AGR620CFAG.VISTE00001 VISTELEFONO ON SRBISD.IDCUNO=VISTELEFONO.NFNANO 
		LEFT JOIN AGR620CFAG.SROORSPL SRBSOL ON SRBISD.IDOLIN = SRBSOL.OLLINE AND SRBISD.IDORNO = SRBSOL.OLORNO 
		LEFT JOIN AGR620CFAG.SROPRG SRBPRG ON SRBISD.IDPRDC = SRBPRG.PGPRDC 
		LEFT JOIN AGR620CFAG.SROHNH SROHNH ON SRBISD.IDINUM = SROHNH.IHINUM 
		LEFT JOIN AGR620CFAG.SROISH SRBISH_1 ON SROHNH.IHRFNR = SRBISH_1.IHINVN AND SROHNH.IHCUNO = SRBISH_1.IHCUNO 
		LEFT JOIN AGR620CFAG.SROORSHE SRBSOH_1 ON SRBISH_1.IHORNO = SRBSOH_1.OHORNO 
		LEFT JOIN AGR620CFAG.SROORSHE SRBSOH ON SRBISH.IHORNO = SRBSOH.OHORNO 
		LEFT JOIN AGR620CFAG.SROCTLPB SRBCTLPB ON SRBPRG.PGPRFA = SRBCTLPB.PBPRFA 
		LEFT JOIN AGR620CFAG.SROCTLSD SRBCTLSD ON SRBISH.IHSALE = SRBCTLSD.CTSIGN 
		LEFT JOIN AGR620CFAG.SROCTLSD SRBCTLSD_1 ON SRBISH_1.IHSALE = SRBCTLSD_1.CTSIGN 
		LEFT JOIN AGR620CFAG.SROGTP SRBGTP ON SRBPRG.PGGTPE = SRBGTP.GTGTPE 
		LEFT JOIN AGR620CFAG.SROCTLC5 SRBCTLC5 ON CTNCA5=NANCA5 
WHERE
	((CASE SRBISH.IHTYPP WHEN 1 THEN SRBISD.IDQTY ELSE SRBISD.IDQTY * -1 END )<> 0) 
AND (SRBSOH.OHORDT <> '75' AND SRBSOH.OHORDT <> '69' AND SRBSOH.OHORDT<> '70' ) 
AND (SRBSOH.OHORDT <> '24') 
AND (SRBSOH.OHORDT <> '71') 
AND (SRBSOH.OHORDT <> '02') 
AND (SRBSOH.OHORDT <> '33') 
AND (SRBSOH.OHORDT <> '73') 
AND (SRBSOH.OHORDT <> '72') 
AND (SRBSOH.OHORDT <> '25') 
AND (SRBSOH.OHORDT <> '65') 
AND (SRBSOH.OHORDT <> '60') 
AND (SRBSOH.OHORDT <> 'SG') 
AND (SRBSOH.OHORDT <> 'SR') 
AND (SRBSOH.OHORDT <> 'EG') 
AND (SRBSOH.OHORDT <> 'ER') 
AND (SRBSOH.OHORDT <> '66') 
AND (SRBSOH.OHORDT <> '67') 
AND (SRBSOH.OHORDT <> '76') 
AND (SRBSOH.OHORDT <> 'N2') 
AND (SRBSOH.OHORDT <> '77') 
AND (SRBSOH.OHORDT <> '68') 
AND (SRBSOH.OHORDT <> 'SN') 
AND (SRBSOH.OHORDT <> 'Z3') 
AND (SRBSOH.OHORDT <> 'Z5') 
AND (SRBSOH.OHORDT <> 'Z6') 
AND (SRBSOH.OHORDT <> 'Z7') 
AND (SRBSOH.OHORDT <> 'ZM') 
AND (SRBSOH.OHORDT <> 'ZN') 
AND (SRBSOH.OHORDT <> 'K9') 
AND (SRBSOH.OHORDT <> 'R7') 
AND (SRBSOH.OHORDT <> 'K4') 
AND (SRBSOH.OHORDT <> 'Z4') 
AND SRBISD.IDLINE < 8000 
AND SRBISH.IHODAT ='".$fechas[ FECHA_ORDEN ]."'	
AND SRBSOL.OLORDS =60
UNION ALL 

SELECT DISTINCT 
	SROORSHE.OHORDT AS TIPO, 
	SRBISH.IHINVN AS FACTURA, 
	SRBISH.IHIDAT AS FECHA_FACTURA, 
	SRBISH.IHODAT AS FECHA_ORDEN, 
	SRBISD.IDCUNO AS CEDULA, 
	SRBNAM.NANAME AS NOMBRE_CLIENTE, 
	SRBISD.IDSROM AS BODEGA, 
	CASE SRBISD.IDINUM WHEN 0 THEN SRBISH.IHSALE ELSE SRBISH_1.IHSALE END AS VENDEDOR, 
	CASE SRBISD.IDINUM WHEN 0 THEN SRBCTLSD.CTNAME ELSE SRBCTLSD_1.CTNAME END AS DES_VENDE, 
	CASE SRBISD.IDINUM WHEN 0 THEN SROORSHE.OHHAND ELSE SRBSOH_1.OHHAND END AS CALL, 
	CASE SRBISD.IDINUM WHEN 0 THEN SRBCTLSD.CTSMAN ELSE SRBCTLSD_1.CTSMAN END AS MANEJADOR, 
	SRBISD.IDOLIN AS LINEA_ORDEN, 
	SRBPRG.PGPRDC AS ITEM,
	SRBPRG.PGDESC AS Descripcion, 
	CASE WHEN SRBISD.IDFOCC='N' THEN 0 ELSE 1 END AS FOC, 
	CASE WHEN (SRBPRG.PGPDGR='G03' AND (SRBCTLSD.CTSMAN='ADMINISTRA' OR SRBCTLSD_1.CTSMAN='ADMINISTRA') AND (SROORSHE.OHHAND='VEND999' OR SRBSOH_1.OHHAND='VEND999')) THEN 'AGI' 
	WHEN (SRBPRG.PGPDGR='G04' AND (SRBCTLSD.CTSMAN='ADMINISTRA' OR SRBCTLSD_1.CTSMAN='ADMINISTRA') AND (SROORSHE.OHHAND='VEND999' OR SRBSOH_1.OHHAND='VEND999')) THEN 'AMI' 
	ELSE SRBPRG.PGPGRP END GRUPO, 
	SRBPRG.PGISET AS SEGMENTO,
	CASE WHEN (SRBCTLPB.PBDESC='IMPORTADOS' AND SRBPRG.PGPDGR='G03' AND (SRBCTLSD.CTSMAN='ADMINISTRA' OR SRBCTLSD_1.CTSMAN='ADMINISTRA') AND (SROORSHE.OHHAND='VEND999' OR SRBSOH_1.OHHAND='VEND999')) THEN 'AGI' 
	WHEN (SRBCTLPB.PBDESC='IMPORTADOS' AND SRBPRG.PGPDGR='G04' AND (SRBCTLSD.CTSMAN='ADMINISTRA' OR SRBCTLSD_1.CTSMAN='ADMINISTRA') AND (SROORSHE.OHHAND='VEND999' OR SRBSOH_1.OHHAND='VEND999')) THEN 'AMI' 
	ELSE SRBCTLPB.PBDESC END FAMILIA,
	(CASE SRBISH.IHTYPP WHEN 1 THEN SRBISD.IDQTY ELSE SRBISD.IDQTY * -1 END) AS CANTIDAD, 
	CASE WHEN SRBSOL.OLFOCC='Y' THEN 0 ELSE SRBSOL.OLITET END AS VALORSINIVA, 
	CASE SRBISD.IDTYPP WHEN 1 THEN SRBISD.IDITT ELSE SRBISD.IDITT*-1 END AS IVA, 
	CASE WHEN SRBSOL.OLFOCC='Y' THEN 0 ELSE SRBSOL.OLITIT END AS VALOR,
	(CASE 
	WHEN SROORSHE.OHHAND<>SRBCTLSD.CTSIGN OR SRBCTLSD.CTSMAN='MERCADEO' THEN 'MERCADEO'
	WHEN SROORSHE.OHHAND<>SRBCTLSD.CTSIGN OR SROORSHE.OHCUNO IN ('900423563') THEN 'PESTAR'
	WHEN SROORSHE.OHHAND<>SRBCTLSD.CTSIGN OR SROORSHE.OHSALE='VEND157' OR SROORSHE.OHSALE ='SUAREZM' OR SROORSHE.OHSALE ='SUAREZC' OR SROORSHE.OHSALE = 'VEND217' OR SROORSHE.OHCUNO IN ('800159998') THEN 'INSTITUCIONAL' 
	WHEN SROORSHE.OHHAND<>SRBCTLSD.CTSIGN OR SROORSHE.OHHAND='MARTINEZF' OR SROORSHE.OHHAND ='RODRIGUEZJ' THEN 'TRASLADOS'
	WHEN SROORSHE.OHHAND<>SRBCTLSD.CTSIGN OR SROORSHE.OHHAND ='ALIANZAS' OR SROORSHE.OHHAND ='NETSTORE' OR SROORSHE.OHHAND ='VEND528' OR SROORSHE.OHHAND ='VEND561' OR SROORSHE.OHSALE ='VEND417' OR SROORSHE.OHCUNO IN ('1056028493',          '9007487391', '900844137',   '901295969',             '1020775290', '10207752909',           '901128047',    '9011280475', '900041991',   '9006676820',             '79592537',      '901325040',   '1098716630', '901425454',    '901333960',   '52970714',      '900525765',             '9008438989', '9008438984', '9008438981', '9008438982', '901110407',   '9011104074', '1056028493',             '9007487391', '900844137',   '901295969',   '901128047',    '1020775290', '10207752909',             '9011280475', '900770206',   '9007702068', '52430443',      '9006676820', '79592537',      '901325040',             '1098716630', '901425454',   '901333960', '900839095', '9008390956') THEN 'CANALES DIGITALES'
	WHEN SROORSHE.OHHAND<>SRBCTLSD.CTSIGN OR SROORSHE.OHHAND LIKE 'VENDWEB%' OR SROORSHE.OHHAND LIKE 'DIGITAL%' OR SROORSHE.OHHAND='INTEGRATOR' OR SROORSHE.OHHAND = 'ESTADISTIC' THEN 'PAGINA WEB'
	WHEN SROORSHE.OHHAND= SRBCTLSD.CTSIGN AND SRBCTLSD.CTSMAN ='VANANDELL' AND SROORSHE.OHHAND <> 'VANANDELL' AND SROORSHE.OHSALE IN ('VEND114', 'VEND214') THEN 'TELEOPERADOR CONSULTORIO'
	WHEN SROORSHE.OHHAND= SRBCTLSD.CTSIGN AND SRBCTLSD.CTSMAN ='VANANDELL' AND SROORSHE.OHHAND <> 'VANANDELL' THEN 'TELEOPERADOR EXTERNA'
	WHEN SROORSHE.OHHAND= SRBCTLSD.CTSIGN OR SROORSHE.OHSALE ='VENDECOM' THEN 'CALLCENTER'
	WHEN SROORSHE.OHHAND<>SRBCTLSD.CTSIGN OR SRBCTLSD.CTSMAN='VANANDELL' AND SROORSHE.OHSALE = 'VENDOTC' THEN 'VENTA EXTERNA LICITACIONES'
	WHEN SROORSHE.OHHAND<>SRBCTLSD.CTSIGN OR SRBCTLSD.CTSMAN='ADMINISTRA' OR SROORSHE.OHHAND LIKE 'CAJA%' OR SROORSHE.OHHAND='VEND999' THEN 'ALMACEN'
	WHEN SROORSHE.OHHAND<>SRBCTLSD.CTSIGN OR SRBCTLSD.CTSMAN='VANANDELL' THEN 'VENTA EXTERNA'
	END) AS SECTOR
FROM 
			AGR620CFAG.SROORSHE SROORSHE 
	LEFT JOIN AGR620CFAG.SROORSPL SRBSOL ON SROORSHE.OHORNO = SRBSOL.OLORNO 
	LEFT JOIN AGR620CFAG.SRONAM SRBNAM ON SRBNAM.NANUM=SROORSHE.OHCUNO 
	LEFT JOIN AGR620CFAG.VISTE00001 VISTELEFONO ON SROORSHE.OHCUNO=VISTELEFONO.NFNANO 
	LEFT JOIN AGR620CFAG.SROPRG SRBPRG ON SRBSOL.OLPRDC = SRBPRG.PGPRDC 
	LEFT JOIN AGR620CFAG.SROCTLSD SRBCTLSD ON SROORSHE.OHSALE = SRBCTLSD.CTSIGN 
	LEFT JOIN AGR620CFAG.SROCTLPB SRBCTLPB ON SRBPRG.PGPRFA = SRBCTLPB.PBPRFA 
	LEFT JOIN AGR620CFAG.SROCTLD1 SROCTLD1 ON SROCTLD1.CTOTYP=SRBSOL.OLORDT 
	LEFT JOIN AGR620CFAG.SROGTP SRBGTP ON SRBPRG.PGGTPE = SRBGTP.GTGTPE 
	LEFT JOIN AGR620CFAG.SROCTLC5 SRBCTLC5 ON CTNCA5=NANCA5 
	LEFT JOIN AGR620CFAG.SROISH SRBISH on SRBISH.IHORNO = SROORSHE.OHORNO 
	LEFT JOIN AGR620CFAG.SROISDPL SRBISD ON SRBISH.IHINVN = SRBISD.IDINVN AND SRBISH.IHORNO = SRBISD.IDORNO 
	LEFT JOIN AGR620CFAG.SROHNH SROHNH ON SRBISD.IDINUM = SROHNH.IHINUM 
	LEFT JOIN AGR620CFAG.SROISH SRBISH_1 ON SROHNH.IHRFNR = SRBISH_1.IHINVN AND SROHNH.IHCUNO = SRBISH_1.IHCUNO 
	LEFT JOIN AGR620CFAG.SROORSHE SRBSOH_1 ON SRBISH_1.IHORNO = SRBSOH_1.OHORNO 
	LEFT JOIN AGR620CFAG.SROCTLSD SRBCTLSD_1 ON SRBISH_1.IHSALE = SRBCTLSD_1.CTSIGN 
WHERE 
		(SROORSHE.OHSTAT <> 'D') 
	AND (SROORSHE.OHORDT <> 'R5') 
	AND (SROORSHE.OHORDT <> 'R6') 
	AND (SROORSHE.OHORDT <> 'R8') 
	AND (SROORSHE.OHORDT <> '75') 
	AND (SROORSHE.OHORDT <> '69') 
	AND (SROORSHE.OHORDT <> '70' ) 
	AND (SROORSHE.OHORDT <> '24') 
	AND (SROORSHE.OHORDT <> '71') 
	AND (SROORSHE.OHORDT <> '02') 
	AND (SROORSHE.OHORDT <> '33') 
	AND (SROORSHE.OHORDT <> '73') 
	AND (SROORSHE.OHORDT <> '72') 
	AND (SROORSHE.OHORDT <> '25') 
	AND (SROORSHE.OHORDT <> '65') 
	AND (SROORSHE.OHORDT <> '60') 
	AND (SROORSHE.OHORDT <> 'SG') 
	AND (SROORSHE.OHORDT <> 'SR') 
	AND (SROORSHE.OHORDT <> 'EG') 
	AND (SROORSHE.OHORDT <> 'ER') 
	AND (SROORSHE.OHORDT <> '66') 
	AND (SROORSHE.OHORDT <> '67') 
	AND (SROORSHE.OHORDT <> '76') 
	AND (SROORSHE.OHORDT <> 'N2') 
	AND (SROORSHE.OHORDT <> '77') 
	AND (SROORSHE.OHORDT <> 'Z3') 
	AND (SROORSHE.OHORDT <> 'Z5') 
	AND (SROORSHE.OHORDT <> 'Z6') 
	AND (SROORSHE.OHORDT <> 'Z7') 
	AND (SROORSHE.OHORDT <> 'ZM') 
	AND (SROORSHE.OHORDT <> 'ZN') 
	AND (SROORSHE.OHORDT <> 'K9') 
	AND (SROORSHE.OHORDT <> '68') 
	AND (SROORSHE.OHORDT <> 'SN') 
	AND (SROORSHE.OHORDT <> 'R7') 
	AND (SROORSHE.OHORDT <> 'K4') 
	AND (SROORSHE.OHORDT <> 'Z4') 
	AND (SRBSOL.OLSTAT   <> 'D') 
	AND SRBSOL.OLORDS=60
	AND SRBISH.IHODAT ='".$fechas[ FECHA_ORDEN ]."'"
);
}
	// AND (SRBSOL.OLORDS=10 OR SRBSOL.OLORDS=20 OR SRBSOL.OLORDS=30 OR SRBSOL.OLORDS=45)
    //  echo $sql_ibs_1_meses.'<br><br><br>';

    $rta_sql_ibs = $db2conp->conectar( $sql_ibs_1_meses );
    while( $datos = odbc_fetch_array( $rta_sql_ibs ) ) {
        $arreglo_insert_table = "('$datos[TIPO]','$datos[FACTURA]','$datos[FECHA_FACTURA]','$datos[FECHA_ORDEN]','$datos[CEDULA]','".str_replace( ',', '', str_replace( '.', '', str_replace( "'", '', remove_characters( $datos[ NOMBRE_CLIENTE ] ) ) ) )."','$datos[BODEGA]','$datos[VENDEDOR]','".str_replace( ',', '', str_replace( '.', '', remove_characters( $datos[ DES_VENDE ] ) ) ) ."','$datos[CALL]','$datos[MANEJADOR]',$datos[LINEA],'$datos[ITEM]','".remove_characters( $dato[ Descripcion ] )."',$datos[FOC],'$datos[GRUPO]','$datos[SEGMENTO]','$datos[FAMILIA]',$datos[CANTIDAD],$datos[VALORSINIVA],$datos[IVA],$datos[VALOR],'-','$datos[SECTOR]')";
        // kecho $datos['SECTOR'];
		// echo "$insert_detalle_fac $arreglo_insert_table <br><br>";
        $sqlcon->insertar( $insert_detalle_fac.$arreglo_insert_table );
    }
}

$time_post = microtime( true );
$exec_time = $time_post - $time_pre;
// // echo( $exec_time/60 ).'<br> Terminó...';

mssql_close();
mssql_free_result();
odbc_close_all();
echo "<center> TODO OK</center>";
?>
